### ISSUE TITLE
Questions on Data Harvesting

### ISSUE THREAD

**Issue by Perfect-Mike** [Leighm0/enphase_gateway#1]
Hi Leigh, 

Thanks for creating this driver, it looks really great. I've implemented it on one of my test projects and we instantly managed to integrate the device and started to get data almost immediately. 

However, we didn't get all the data, please see the following pics. We haven't received any data values for Energy Consumption, Excess KW and Grid Power KW.

I don't know if there are any settings we should be looking at, or if we need to have an Enlighten API Licence?

![Capture-Composer-Variables-DataValues](https://github.com/Leighm0/enphase_gateway/assets/155421599/05fbc5a8-e209-4503-a1b1-314fdbd8daa3)

![Capture-Composer-SystemDesign-DataValues](https://github.com/Leighm0/enphase_gateway/assets/155421599/dd813276-951c-4166-a969-cc811ee7c180)

Thanks again, keen to hear what your thoughts are.

**Comment by Leighm0** [comment]
Hi Mike,

Firstly can I ask which Enphase Gateway model do you have (if you are unsure, can you send me a photo?)

Since you appear to be on Firmware v7, you need to populate the username and password fields with your Enphase Enlighten account credentials (they do not need to be special developer ones just the one which has access to your system).

Going off what I'm seeing it appears your gateway isn't giving out any Consumption values for some reason (which is also needed to calculate excess solar and grid data), the consumption values only get populated if you have the Enphase Envoy Metered version with the CTs connected to your meter box... so it sounds like you are using a Non-metered Gateway, which isn't supported..

**Comment by Perfect-Mike** [comment]
Thanks Leigh, 

I'll have to check, we didn't do the Solar installation, but the team who did are pretty good, so they should know what was connected. This project does have Tesla Batteries and Tesla Gateway, so it may be that those are connected to each other for the data.

The Enphase Gateway has the Part No: 800-00654-r08

Not sure if that indicates what the model might be?

We've got the credentials and the driver is connected, so it seems like the system was pulling in some of the data, and I was hoping it was just a configuration we had wrong. I'll get a photo of the gateway tomorrow if I can get back into the project.

Have a good one.

**Comment by Leighm0** [comment]
Hi Mike,

Can you please try Version 17 I just uploaded and see if it fixes your missing Consumption values.  Thanks

**Comment by Perfect-Mike** [comment]
That works, thanks for resolving that. 
We're going to now try and work with the variables to create a schedule for the AirCon to run in a dry mode, when the humidity is high and there is extra solar capacity.

Always love to try and do something innovative on a project. 
Thanks for creating the driver, if we can get it to function in our application we will report back with our progress, application notes and donate.
